// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class Configuration
{
    public int ConfigId { get; set; }

    public string ConfigKey { get; set; }

    public string ConfigValue { get; set; }

    public string UserId { get; set; }
}