// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class JusticeExchangeBatch
{
    public long JusticeExchangeBatchId { get; set; }

    public long ScreeningLogicBatchId { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }

    public virtual ScreeningLogicBatch ScreeningLogicBatch { get; set; }
}