// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class JusticeLogicPersonSummaryLink
{
    public long JusticeLogicPersonSummaryLinkId { get; set; }

    public long ScreeningLogicScrappingId { get; set; }

    public string SummaryLink { get; set; }

    public virtual ICollection<PersonSummary> PersonSummaries { get; set; } = new List<PersonSummary>();

    public virtual ScreeningLogicScrapping ScreeningLogicScrapping { get; set; }
}