// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class PersonRecord
{
    public long PersonRecordId { get; set; }

    public long PersonSummaryId { get; set; }

    public string RecordType { get; set; }

    public string RecordDescription { get; set; }

    public string RecordNumber { get; set; }

    public string RecordDate { get; set; }

    public string Ssn { get; set; }

    public string Dob { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string MiddleName { get; set; }

    public string Agency { get; set; }

    public string RecordDetailLink { get; set; }

    public virtual ICollection<PersonAlias> PersonAliases { get; set; } = new List<PersonAlias>();

    public virtual PersonSummary PersonSummary { get; set; }
}