// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class PersonAlias
{
    public long PersonAliasId { get; set; }

    public long PersonRecordId { get; set; }

    public string Alias { get; set; }

    public virtual PersonRecord PersonRecord { get; set; }
}