// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class PersonSummary
{
    public long PersonSummaryId { get; set; }

    public long JusticeLogicPersonSummaryLinkId { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Middlename { get; set; }

    public string Dob { get; set; }

    public string Ssn { get; set; }

    public string PdfDataFilePath { get; set; }

    public virtual JusticeLogicPersonSummaryLink JusticeLogicPersonSummaryLink { get; set; }

    public virtual ICollection<PersonRecord> PersonRecords { get; set; } = new List<PersonRecord>();
}