// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class ProcessStartAndStop
{
    public byte ProcessStartAndStopId { get; set; }

    public bool IsStarted { get; set; }

    public bool Stop { get; set; }

    public int MaxRecordsToProcess { get; set; }
}