// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class ProcessingSchedule
{
    public int ProcessingScheduleId { get; set; }

    public byte DayOfWeek { get; set; }

    public bool IsTurnedOff { get; set; }

    public TimeSpan? StartTime { get; set; }

    public TimeSpan? StopTime { get; set; }

    public TimeSpan? MaintenanceStartTime { get; set; }

    public TimeSpan? MaintenanceStopTime { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }
}
