// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScreeningLogicServiceApp.Models;

public partial class ScreeningLogicScrapping
{
    public long ScreeningLogicScrappingId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string MiddleName { get; set; }

    public string Dob { get; set; }

    public string Ssn { get; set; }

    public string ScrappedLink { get; set; }

    public string OrderId { get; set; }

    public string SubOrderId { get; set; }

    public bool IsValidData { get; set; }

    public bool IsSentToBackgroundScreening { get; set; }

    public bool IsDataFoundInBackgroundScreening { get; set; }

    public bool IsDataUpdatedInScreeningLogic { get; set; }

    public DateTime? ScrappingDate { get; set; }

    public DateTime? SentToBackgroundScreeningDate { get; set; }

    public string CriminalDetailFormLink { get; set; }

    public string PersonDataSummary { get; set; }

    public long? ScreeningLogicBatchId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<JusticeLogicPersonSummaryLink> JusticeLogicPersonSummaryLinks { get; set; } = new List<JusticeLogicPersonSummaryLink>();

    public virtual ScreeningLogicBatch ScreeningLogicBatch { get; set; }
}